### PR TITLE
Add chinese support

### PR DESCRIPTION
**Pull request by Pandorym**
The width of a Chinese is equal to two in English.

### CODE REVIEW

**Comment by hustcc** [comment]
What is the meaning of `中`?

```js
const wordWidth = text => (text ? text.length + (`${text}中`.match(/[^\x00-\x80]/g).length - 1) : 0);
```

Can be change to 

```js
const wordWidth = text => (text ? text.length + text.match(/[^\x00-\x80]/g).length : 0);
```

**Comment by Pandorym** [comment]
This is to make the `text.match !== null`, **Any Chinese character** can replace "中",

Consider the following : 
```JavaScript
const wordWidth = text => (text ? text.length + text.match(/[^\x00-\x80]/g).length : 0);
let str = 'english';  // Any pure English string
wordWidth(str);       // throw Uncaught TypeError: Cannot read property 'length' of null
```

**Comment by hustcc** [comment]
Feels not very perfect.

There has a module named `word-width`, but it is too large.

**Comment by Pandorym** [comment]
I think that is worth import it. We don't know the language that the user needs to use.

This is unusable if a character should be wide 2, but `wordWidth  == 1`.

**Comment by hustcc** [comment]
Because of the size of module, we remove it temporarily.

**Pull request merged**
